---
title: "exploratory"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(janitor)
library(viridis)

options(tigris_use_cache = TRUE)

theme_set(theme_minimal())
my_census_key <- "a16f3636406d2b544871e2ae49bb318c3ddcacba"
census_api_key(my_census_key)

census_vars <- load_variables(2010, "sf1", cache = TRUE)
```

```{r eval=FALSE}
read_csv("data/Opioid_Dispensation_Data_County_Quarter_3_2016_-_Current_Health.csv") %>% 
  clean_names() -> data

data
```

```{r eval=FALSE}
data %>% 
  mutate(county_name = str_c(str_to_title(county_name), " County"),
         county_name = str_replace(county_name, "Mckean", "McKean"),
         time_period = factor(time_period)) -> df
df
```


```{r eval=FALSE}
colnames(data)

data %>% 
  distinct(latitude_longitude)

data %>% 
  distinct(time_period)


data %>% 
  filter(county_name == "ALLEGHENY") %>% 
```

```{r}
get_acs(geography = "county",
        variables = "B01003_001", 
        state = "PA",
        geometry = TRUE) -> pa_geo

pa_geo %>% 
  mutate(NAME = str_replace(NAME, ", Pennsylvania", "")) -> df_geo_county
```

```{r}
df_geo_county %>% 
  left_join(df_dispensation, by = c("NAME" = "county_name")) %>% 
  filter(time_period == "2017 Q3",
         type_of_drug_class == "Opioids (All Schedules)",
         type_of_rate_or_count_measure == "Dispensations per 1,000 Population") %>% 
  ggplot(aes(fill = rate_or_count)) +
  geom_sf() +
  scale_fill_viridis_c()
```
```{r}
df_geo_county %>% 
  left_join(df_seizures_arrests, by = c("NAME" = "county_name")) %>% 
  filter(time_period == "2017 Q3",
         type_of_drug_class == "Opioids (All Schedules)",
         type_of_rate_or_count_measure == "Dispensations per 1,000 Population") %>% 
  ggplot(aes(fill = rate_or_count)) +
  geom_sf() +
  scale_fill_viridis_c()
```
