---
title: "pa county OD pca"
author: "Conor Tompkins"
date: "September 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(tidycensus)
library(sf)
library(janitor)
library(viridis)
library(scales)
library(ggfortify)
library(ggrepel)

options(tigris_use_cache = TRUE)

theme_set(theme_minimal())
my_census_key <- "a16f3636406d2b544871e2ae49bb318c3ddcacba"
census_api_key(my_census_key)

census_vars <- load_variables(2010, "sf1", cache = TRUE)

source("scripts/data_cleaning.R")

options(scipen = 999)
```

```{r}
#df_dispensation %>% 
#  filter(county_name != "Pennsylvania County") %>% 
#  distinct(county_name) %>% 
#  mutate(year = 2017) -> df_counties

get_acs(geography = "county",
        variables = "B01003_001", 
        state = "PA",
        geometry = TRUE) -> pa_geo

pa_geo %>% 
  mutate(county_name = str_replace(NAME, ", Pennsylvania", "")) %>% 
  select(-NAME) -> df_geo_county
```

```{r}
df_dispensation %>% 
  select(county_name, year, quarter, time_measure, type_of_drug_class, type_of_rate_or_count_measure, dispensation_count = rate_or_count) %>% 
  filter(type_of_rate_or_count_measure == "Number of Dispensations",
         type_of_drug_class == "Opioids (All Schedules)",
         time_measure == "Quarterly Counts",
         year == 2017) %>% 
  group_by(county_name, year) %>% 
  summarize(dispensation_count = sum(dispensation_count)) -> df_dispensation_clean
```

```{r}
df_seizures_arrests %>% 
  select(county_name, year, qtr, drug, drug_quantity, incident_count, arrests) %>% 
  filter(year == 2017) %>% 
  spread(drug, drug_quantity) %>% 
  replace_na(list(Fentanyl = 0,
                      Heroin = 0,
                      Opium = 0)) %>% 
  group_by(county_name, year) %>% 
  summarize_at(vars(incident_count:Opium), sum) -> df_seizures_arrests_clean
```

```{r}
df_geo_county %>% 
  left_join(df_dispensation_clean) %>% 
  left_join(df_seizures_arrests_clean) %>% 
  mutate(dispensation_count = (dispensation_count / estimate) * 1000,
         incident_count = (incident_count / estimate) * 1000,
         arrests = (arrests / estimate) * 1000,
         Fentanyl = (Fentanyl / estimate) * 1000,
         Opium = (Opium / estimate) * 1000,
         Heroin = (Heroin / estimate) * 1000) -> df_test
```

```{r}
df_test %>%
  select(-c(GEOID, variable, estimate, moe, year)) %>% 
  na.omit() %>% 
  st_set_geometry(NULL) %>% 
  remove_rownames() %>% 
  column_to_rownames(var = "county_name") -> df_pca

df_pca %>% 
  prcomp(scale = TRUE) -> pc
```

```{r}
pc %>% 
  tidy("pcs") %>%
  select(-std.dev) %>% 
  gather(measure, value, -PC) %>% 
  mutate(measure = case_when(measure == "percent" ~ "Percent",
                             measure == "cumulative" ~ "Cumulative")) %>% 
    ggplot(aes(PC, value)) +
    geom_line() +
    geom_point() +
    facet_wrap(~measure) +
    labs(title = "Variance explained by each principal component",
         x = "Principal Component",
         y = NULL) +
    scale_x_continuous(breaks = 1:8) +
    scale_y_continuous(label = percent) +
  theme_bw()
```

```{r}
df_test %>%
  select(-c(GEOID, variable, estimate, moe, year)) %>% 
  na.omit() %>% 
  st_set_geometry(NULL) %>% 
  nest() %>% 
  mutate(pca = map(data, ~ prcomp(.x %>% select(-county_name), 
                                  center = TRUE, scale = TRUE)),
         pca_aug = map2(pca, data, ~augment(.x, data = .y))) -> df_pca2

df_pca2 %>% 
mutate(
    pca_graph = map2(
      .x = pca,
      .y = data,
      ~ autoplot(.x, loadings = TRUE, loadings.label = TRUE,
                 loadings.label.repel = TRUE,
                 data = .y) +
        theme_bw() +
        labs(x = "Principal Component 1",
             y = "Principal Component 2",
             title = "First two principal components of PCA on PA Opioid data")
    )
  ) %>%
  pull(pca_graph)
```
```{r}
pc %>% 
  augment() %>% 
  rownames_to_column(var = "county_name") %>% 
  select(-.rownames) %>% 
  mutate(label = case_when(.fittedPC1 < -1 | abs(.fittedPC2) > 1 ~ county_name,
                           .fittedPC1 >= -1 | abs(.fittedPC2) <= 1 ~ "")) -> df_plot

df_plot %>% 
  ggplot(aes(.fittedPC1, .fittedPC2, label = label)) +
  #geom_point()
  geom_label()
```

```{r}
df_geo_county %>% 
  left_join(df_plot) %>% 
  gather(pc_name, pc_value, -c(GEOID:county_name, label, geometry)) %>% 
  ggplot(aes(fill = pc_value)) +
  geom_sf() +
  facet_wrap(~pc_name) +
  scale_fill_viridis_c()
```

```{r}
df_geo_county %>% 
  left_join(df_plot) %>% 
  gather(pc_name, pc_value, -c(GEOID:county_name, label, geometry)) %>% 
  filter(pc_name == ".fittedPC1") %>% 
  mutate(county_name = str_replace(county_name, " County", "")) %>% 
  ggplot(aes(reorder(county_name, desc(pc_value)), pc_value, fill = pc_value)) +
  geom_col() +
  coord_flip() +
  scale_fill_viridis_c() +
  theme(panel.grid.minor = element_blank())
```

```{r}
df_geo_county %>% 
  left_join(df_plot) %>% 
  gather(pc_name, pc_value, -c(GEOID:county_name, label, geometry)) %>% 
  filter(pc_name == ".fittedPC3") %>% 
  mutate(county_name = str_replace(county_name, " County", "")) %>% 
  ggplot(aes(reorder(county_name, desc(pc_value)), pc_value, fill = pc_value)) +
  geom_col() +
  coord_flip() +
  scale_fill_viridis_c() +
  theme(panel.grid.minor = element_blank())
```

```{r}
df_test %>% 
  mutate_at(vars(dispensation_count:Opium), scale) %>% 
  gather(measure, value, -c(GEOID:year, geometry)) %>% 
  ggplot(aes(fill = value)) +
  geom_sf() +
  scale_fill_viridis_c() +
  facet_wrap(~measure)
```

```{r}
df_test %>% 
  ggplot(aes(fill = dispensation_count)) +
  geom_sf() +
  scale_fill_viridis_c()

df_test %>% 
  ggplot(aes(fill = incident_count)) +
  geom_sf() +
  scale_fill_viridis_c()

df_test %>% 
  ggplot(aes(fill = arrests)) +
  geom_sf() +
  scale_fill_viridis_c()

df_test %>% 
  ggplot(aes(fill = Fentanyl)) +
  geom_sf() +
  scale_fill_viridis_c()

df_test %>% 
  ggplot(aes(fill = Heroin)) +
  geom_sf() +
  scale_fill_viridis_c()

df_test %>% 
  ggplot(aes(fill = Opium)) +
  geom_sf() +
  scale_fill_viridis_c()


```


